version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: db
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-app}

    ports:
      - "${POSTGRES_PORT:-5432}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-app}" ]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - default_network

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: app
    restart: unless-stopped

    depends_on:
      db:
        condition: service_healthy

    environment:
      NODE_ENV: development
      NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL:-http://localhost:3000}

      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-app}
      # Already set in Dockerfile, but can override here if needed
      # CHOKIDAR_USEPOLLING: "true"
      # WATCHPACK_POLLING: "true"

    ports:
      - "3000:3000"

    volumes:

      # Use when not on Mac
      # - .:/app

      # Use :delegated on Mac for better performance
      - .:/app:delegated

      - node_modules:/app/node_modules

      - next_cache:/app/.next

      - bun_cache:/root/.bun

    command: bun run dev

    networks:
      - default_network

networks:
  default_network:


volumes:
  postgres_data:
  node_modules:
  next_cache:
  bun_cache:
